import { NextRequest, NextResponse } from "next/server";
import { isSupabaseConfigured } from "@/lib/db/with-fallback";
import * as db from "@/lib/db";
import { getMosqueSlugFromRequest } from "@/lib/tenant";
import {
  requireAdminApiAuth,
  requireAdminApiPermission,
} from "@/lib/auth/api";
import { writeAuditLog } from "@/lib/audit";

const SAMPLE_MEMBERS: Array<{
  full_name: string;
  email: string;
  rank: string;
  office_title: string | null;
}> = [
  { full_name: "Sample · James Carter", email: "sample-james@example.com", rank: "Master", office_title: "Lead Imam" },
  { full_name: "Sample · Robert Hughes", email: "sample-robert@example.com", rank: "MM", office_title: "Senior Warden" },
  { full_name: "Sample · Edward Fielding", email: "sample-edward@example.com", rank: "MM", office_title: "Junior Warden" },
  { full_name: "Sample · Thomas Whitaker", email: "sample-thomas@example.com", rank: "PM", office_title: "Treasurer" },
  { full_name: "Sample · Michael Anderson", email: "sample-michael@example.com", rank: "PM", office_title: "Secretary" },
  { full_name: "Sample · Daniel Reyes", email: "sample-daniel@example.com", rank: "MM", office_title: "PastoralCare" },
  { full_name: "Sample · William Pearce", email: "sample-william@example.com", rank: "MM", office_title: "Charity Steward" },
  { full_name: "Sample · George Holmes", email: "sample-george@example.com", rank: "FC", office_title: null },
];

const SAMPLE_LEADS: Array<{
  first_name: string;
  last_name: string;
  email: string;
  stage: string;
}> = [
  { first_name: "Sample", last_name: "Aaron Webb", email: "sample-newcomer-aaron@example.com", stage: "new" },
  { first_name: "Sample", last_name: "Henry Patel", email: "sample-newcomer-henry@example.com", stage: "interview_scheduled" },
  { first_name: "Sample", last_name: "Oliver King", email: "sample-newcomer-oliver@example.com", stage: "membership decision_pending" },
];

function isSampleEmail(email: string | null | undefined): boolean {
  if (!email) return false;
  return email.startsWith("sample-") && email.endsWith("@example.com");
}

export async function POST(request: NextRequest) {
  const unauthorized = await requireAdminApiAuth();
  if (unauthorized) return unauthorized;
  if (!isSupabaseConfigured()) {
    return NextResponse.json(
      { error: "Database not configured." },
      { status: 503 }
    );
  }
  const mosqueSlug = getMosqueSlugFromRequest(request);
  const mosqueId = await db.resolveMosqueId(mosqueSlug);
  if (!mosqueId) {
    return NextResponse.json({ error: "Mosque not found." }, { status: 404 });
  }
  const forbidden = await requireAdminApiPermission("admin:all", mosqueId);
  if (forbidden) return forbidden;

  const created = { members: 0, newcomers: 0, events: 0, giving: 0, donations: 0 };

  const existingMembers = await db.getMembers(mosqueId, {});
  const existingEmails = new Set(existingMembers.map((m) => m.email?.toLowerCase()));
  for (const m of SAMPLE_MEMBERS) {
    if (existingEmails.has(m.email)) continue;
    try {
      await db.createMember(mosqueId, {
        full_name: m.full_name,
        email: m.email,
        phone: null,
        rank: m.rank,
        membership_status: "active",
        address_line_1: null,
        address_line_2: null,
        city: null,
        county: null,
        postcode: null,
        country: "United Kingdom",
        office_title: m.office_title,
        officer_sort_order: null,
        directory_sort_order: null,
        royal_arch: false,
        country_list: false,
        honorary: false,
        dietary_requirements: null,
        date_of_membership: null,
        auth_user_id: null,
        membership_email_sent: false,
        stripe_customer_id: null,
      });
      created.members++;
    } catch {
      // ignore, keep going
    }
  }

  const existingNewcomers = await db.getNewcomers(mosqueId, {});
  const existingNewcomerEmails = new Set(existingNewcomers.map((l) => l.email?.toLowerCase()));
  for (const l of SAMPLE_LEADS) {
    if (existingNewcomerEmails.has(l.email)) continue;
    try {
      await db.addNewcomer(mosqueId, {
        first_name: l.first_name,
        last_name: l.last_name,
        email: l.email,
        phone: null,
        location: null,
        source: "Sample data",
        how_heard_about_us: "Sample data",
        initial_message: "Generated by the sample data starter kit.",
        stage: l.stage,
        assigned_to: null,
        proposer_member_id: null,
        proposer_name: null,
        seconder_member_id: null,
        seconder_name: null,
        next_step: null,
        next_step_due_date: null,
        proposal_date: null,
        membership_decision_date: null,
        interview_completed_at: null,
        consent_given_at: null,
      } as Parameters<typeof db.addNewcomer>[1]);
      created.newcomers++;
    } catch {
      // ignore
    }
  }

  const today = new Date();
  const upcoming = new Date(today);
  upcoming.setDate(upcoming.getDate() + 21);
  const slug = `sample-regular-${upcoming.toISOString().slice(0, 10)}`;
  const existingEvents = await db.getEvents(mosqueId, {});
  const existingSlugs = new Set(existingEvents.map((e) => e.slug));
  if (!existingSlugs.has(slug)) {
    try {
      await db.addEvent(mosqueId, {
        title: "Sample · Regular service",
        slug,
        description: "Demo service created by the sample data starter kit.",
        event_type: "mosque_service",
        event_date: upcoming.toISOString(),
        event_time: "18:30",
        location: "Mark members' Hall",
        temple_room: null,
        dress_code: "Morning dress",
        enable_rsvp: true,
        rsvp_deadline: null,
        max_attendees: null,
        enable_payments: false,
        enable_dining_rsvp: true,
        dining_price: 35,
        dining_description: "Festive board after the service",
        enable_charity_donation: true,
        charity_name: "Mosque Benevolent Fund",
        charity_description: "Supporting members and their families.",
        charity_suggested_amounts: [10, 20, 50, 100],
        charity_allow_custom: true,
        enable_raffle_donation: false,
        raffle_description: "Help fund evening raffle prizes",
        raffle_suggested_amounts: [5, 10, 20, 50],
        raffle_allow_custom: true,
        enable_service_fee: false,
        service_fee_amount: null,
        service_fee_description: null,
        enable_guest_tickets: false,
        guest_ticket_price: null,
        guest_ticket_description: null,
        featured_image_url: null,
        created_by: null,
        published: true,
      } as Parameters<typeof db.addEvent>[1]);
      created.events++;
    } catch {
      // ignore
    }
  }

  const thisYear = today.getFullYear();
  for (const m of SAMPLE_MEMBERS) {
    try {
      await db.createMemberGiving(mosqueId, {
        member_email: m.email,
        member_name: m.full_name,
        member_id: null,
        giving_id: null,
        amount: 200,
        currency: "gbp",
        period_start: `${thisYear}-09-01`,
        period_end: `${thisYear + 1}-08-31`,
        status: "outstanding",
        payment_id: null,
        stripe_payment_intent_id: null,
        stripe_subscription_id: null,
        paid_at: null,
      });
      created.giving++;
    } catch {
      // ignore (e.g. duplicate)
    }
  }

  await writeAuditLog({
    mosqueId,
    action: "sample_data_seeded",
    entityType: "mosque",
    entityId: mosqueId,
    summary: "Sample data starter kit applied",
    metadata: created,
  });

  return NextResponse.json({ ok: true, created });
}

export async function DELETE(request: NextRequest) {
  const unauthorized = await requireAdminApiAuth();
  if (unauthorized) return unauthorized;
  if (!isSupabaseConfigured()) {
    return NextResponse.json(
      { error: "Database not configured." },
      { status: 503 }
    );
  }
  const mosqueSlug = getMosqueSlugFromRequest(request);
  const mosqueId = await db.resolveMosqueId(mosqueSlug);
  if (!mosqueId) {
    return NextResponse.json({ error: "Mosque not found." }, { status: 404 });
  }
  const forbidden = await requireAdminApiPermission("admin:all", mosqueId);
  if (forbidden) return forbidden;

  const removed = { members: 0, newcomers: 0, events: 0 };

  const members = await db.getMembers(mosqueId, {});
  for (const m of members) {
    if (isSampleEmail(m.email)) {
      try {
        await db.archiveMember(m.id, mosqueId, "Sample data cleanup");
        removed.members++;
      } catch {
        // ignore
      }
    }
  }

  const newcomers = await db.getNewcomers(mosqueId, {});
  for (const l of newcomers) {
    if (isSampleEmail(l.email)) {
      try {
        await db.updateNewcomer(l.id, mosqueId, { stage: "declined" });
        removed.newcomers++;
      } catch {
        // ignore
      }
    }
  }

  const events = await db.getEvents(mosqueId, {});
  for (const e of events) {
    if (e.slug.startsWith("sample-regular-")) {
      try {
        await db.updateEvent(e.id, mosqueId, { published: false });
        removed.events++;
      } catch {
        // ignore
      }
    }
  }

  await writeAuditLog({
    mosqueId,
    action: "sample_data_cleared",
    entityType: "mosque",
    entityId: mosqueId,
    summary: "Sample data starter kit cleared",
    metadata: removed,
  });

  return NextResponse.json({ ok: true, removed });
}
