"use client";

import { ArrowLeft, Printer } from "lucide-react";
import Link from "next/link";

type Receipt = {
  id: string;
  date: string;
  status: string;
  currency: string;
  total: number;
  lines: Array<{ label: string; amount: number }>;
  notes: string | null;
  reference: string;
};

export function ReceiptClient({
  kind,
  receipt,
  member,
  mosque,
}: {
  kind: "payment" | "donation" | "giving";
  receipt: Receipt;
  member: { full_name: string; email: string };
  mosque: { name: string; mosque_number: string | null; support_email: string | null } | null;
}) {
  const title =
    kind === "payment"
      ? "Payment receipt"
      : kind === "donation"
        ? "Donation receipt"
        : "Giving receipt";

  return (
    <div className="mx-auto max-w-2xl space-y-4 print:m-0 print:max-w-full">
      <div className="flex items-center justify-between print:hidden">
        <Link
          href="/member/payments"
          className="inline-flex items-center gap-2 text-sm text-slate-500 hover:text-slate-900"
        >
          <ArrowLeft className="h-4 w-4" /> Back
        </Link>
        <button
          type="button"
          onClick={() => window.print()}
          className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700"
        >
          <Printer className="h-4 w-4" /> Print or save as PDF
        </button>
      </div>

      <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white p-8 shadow-sm print:rounded-none print:border-0 print:shadow-none">
        <div className="flex items-start justify-between border-b border-slate-200 pb-6">
          <div>
            <p className="text-xs uppercase tracking-[0.18em] text-slate-500">{title}</p>
            <h1 className="mt-1 text-2xl font-semibold text-slate-900">
              £{receipt.total.toFixed(2)}
            </h1>
            <p className="text-xs text-slate-500">
              {new Date(receipt.date).toLocaleString("en-GB", {
                dateStyle: "long",
                timeStyle: "short",
              })}
            </p>
          </div>
          <div className="text-right">
            <p className="text-sm font-semibold text-slate-900">
              {mosque?.name ?? "Mosque"}
            </p>
            {mosque?.mosque_number && (
              <p className="text-xs text-slate-500">No. {mosque.mosque_number}</p>
            )}
            {mosque?.support_email && (
              <p className="text-xs text-slate-500">{mosque.support_email}</p>
            )}
          </div>
        </div>

        <div className="grid gap-4 border-b border-slate-200 py-6 sm:grid-cols-2">
          <div>
            <p className="text-xs uppercase tracking-wider text-slate-500">Receipt to</p>
            <p className="text-sm font-medium text-slate-900">{member.full_name}</p>
            <p className="text-xs text-slate-500">{member.email}</p>
          </div>
          <div>
            <p className="text-xs uppercase tracking-wider text-slate-500">Reference</p>
            <p className="break-all text-xs font-mono text-slate-700">
              {receipt.reference}
            </p>
            <p className="mt-2 text-xs uppercase tracking-wider text-slate-500">Status</p>
            <p className="text-sm font-medium capitalize text-slate-900">
              {receipt.status}
            </p>
          </div>
        </div>

        <table className="w-full text-sm">
          <thead>
            <tr className="border-b border-slate-200 text-left text-xs uppercase tracking-wider text-slate-500">
              <th className="py-3">Description</th>
              <th className="py-3 text-right">Amount</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-100">
            {receipt.lines.map((line, i) => (
              <tr key={`${line.label}-${i}`}>
                <td className="py-3 text-slate-700">{line.label}</td>
                <td className="py-3 text-right font-medium tabular-nums text-slate-900">
                  £{line.amount.toFixed(2)}
                </td>
              </tr>
            ))}
            <tr className="border-t-2 border-slate-200">
              <td className="py-4 text-sm font-semibold text-slate-900">Total</td>
              <td className="py-4 text-right text-lg font-bold tabular-nums text-slate-900">
                £{receipt.total.toFixed(2)}
              </td>
            </tr>
          </tbody>
        </table>

        {receipt.notes && (
          <p className="mt-6 rounded-xl bg-slate-50 p-4 text-xs text-slate-600">
            {receipt.notes}
          </p>
        )}

        <p className="mt-8 text-[11px] text-slate-400">
          This receipt was generated by the mosque member portal. Keep it for your records.
        </p>
      </div>
    </div>
  );
}
