/**
 * Demo mosque profiles for platform seeding (mock DB + scripts/seed-platform-demo.mjs).
 * Each mosque represents a different UK Muslim community with realistic data.
 */

export type PlatformDemoOfficer = {
  full_name: string;
  office_title: string;
  rank?: string;
};

export type PlatformDemoMosqueProfile = {
  slug: string;
  name: string;
  denomination: string;
  city: string;
  country: string;
  tagline: string;
  governing_body: string;
  mosque_number: string;
  primary_color: string;
  secondary_color: string;
  support_email: string;
  support_phone: string;
  secretary_name: string;
  secretary_phone: string;
  secretary_address: string;
  service_schedule: string;
  service_location: string;
  service_location_url: string | null;
  accessibility_notes: string;
  default_dress_code: string;
  hmrc_charity_reference: string;
  gift_aid_pack_name: string;
  gift_aid_pack_email: string;
  charity_donation_url: string | null;
  officers: PlatformDemoOfficer[];
  /** Additional member names (non-officers). */
  member_names: string[];
  newcomer_names: Array<{ first: string; last: string; stage: string }>;
};

export const PLATFORM_DEMO_MOSQUES: PlatformDemoMosqueProfile[] = [
  {
    slug: "central-jamia-demo",
    name: "Central Jamia Masjid",
    denomination: "Sunni (Hanafi)",
    city: "London",
    country: "United Kingdom",
    tagline: "A welcoming masjid serving the heart of the community.",
    governing_body: "London Mosques Network",
    mosque_number: "4344",
    primary_color: "#0b43b8",
    secondary_color: "#e0f2fe",
    support_email: "office@central-jamia.demo",
    support_phone: "020 7930 8181",
    secretary_name: "Bilal Hussain",
    secretary_phone: "020 7930 8182",
    secretary_address: "2 Smith Square, Westminster, London SW1P 3HZ",
    service_schedule: "Jumu'ah Fridays 13:00 & 13:45. Five daily prayers in congregation.",
    service_location: "Central Jamia Masjid, Smith Square, Westminster, London SW1P 3HZ",
    service_location_url: "https://maps.google.com/?q=Smith+Square+Westminster",
    accessibility_notes: "Ramp access at the main door. Wudu facilities and lift to the women's section.",
    default_dress_code: "Modest dress; please remove shoes before entering the prayer hall.",
    hmrc_charity_reference: "MOSQUEPAY-SUN-4344",
    gift_aid_pack_name: "Central Jamia Masjid Gift Aid",
    gift_aid_pack_email: "treasurer@central-jamia.demo",
    charity_donation_url: "https://donate.mosquepay.demo/central-jamia",
    officers: [
      { full_name: "Imam Yusuf Abdullah", office_title: "Imam", rank: "Imam" },
      { full_name: "Tariq Mahmood", office_title: "Chairman of Trustees", rank: "Leader" },
      { full_name: "Bilal Hussain", office_title: "Secretary", rank: "Member" },
      { full_name: "Aisha Rahman", office_title: "Treasurer", rank: "Member" },
      { full_name: "Omar Farooq", office_title: "Mu'adhin", rank: "Member" },
    ],
    member_names: [
      "Sara Mahmood",
      "Ibrahim Khan",
      "Fatima Ali",
      "Yasin Patel",
      "Khadija Begum",
    ],
    newcomer_names: [
      { first: "Adam", last: "Hussein", stage: "expression_of_interest" },
      { first: "Layla", last: "Iqbal", stage: "initial_contact" },
      { first: "Daniyal", last: "Raza", stage: "service_scheduled" },
    ],
  },
  {
    slug: "madinah-masjid-birmingham",
    name: "Madinah Masjid",
    denomination: "Sunni (Deobandi)",
    city: "Birmingham",
    country: "United Kingdom",
    tagline: "Faith, knowledge and community in the heart of Birmingham.",
    governing_body: "Birmingham Council of Mosques",
    mosque_number: "2187",
    primary_color: "#0f766e",
    secondary_color: "#ecfdf5",
    support_email: "office@madinah-birmingham.demo",
    support_phone: "0121 766 1500",
    secretary_name: "Abdul Rahman Saleh",
    secretary_phone: "0121 766 1501",
    secretary_address: "Belgrave Road, Balsall Heath, Birmingham B12 9QH",
    service_schedule: "Jumu'ah 13:15. Daily prayers and madrasah classes after Maghrib.",
    service_location: "Madinah Masjid, Belgrave Road, Birmingham B12 9QH",
    service_location_url: "https://maps.google.com/?q=Madinah+Masjid+Birmingham",
    accessibility_notes: "Lift to the first-floor prayer hall. Large-print Qur'an copies available.",
    default_dress_code: "Modest dress; head covering for women in the prayer hall.",
    hmrc_charity_reference: "MOSQUEPAY-SUN-2187",
    gift_aid_pack_name: "Madinah Masjid Gift Aid",
    gift_aid_pack_email: "finance@madinah-birmingham.demo",
    charity_donation_url: null,
    officers: [
      { full_name: "Imam Hafiz Suleman", office_title: "Imam", rank: "Imam" },
      { full_name: "Mufti Ismail Desai", office_title: "Resident Scholar", rank: "Leader" },
      { full_name: "Junaid Patel", office_title: "Chairman of Trustees", rank: "Leader" },
      { full_name: "Abdul Rahman Saleh", office_title: "Secretary", rank: "Member" },
      { full_name: "Zainab Variawa", office_title: "Treasurer", rank: "Member" },
    ],
    member_names: ["Anas Vohra", "Maryam Limbada", "Harun Bhana", "Saffiyah Moolla"],
    newcomer_names: [
      { first: "Bilal", last: "Cassim", stage: "approved" },
      { first: "Haaris", last: "Patel", stage: "interview_scheduled" },
    ],
  },
  {
    slug: "al-falah-bradford",
    name: "Al-Falah Islamic Centre",
    denomination: "Sunni (Barelvi)",
    city: "Bradford",
    country: "United Kingdom",
    tagline: "A place of worship, learning and welfare for all generations.",
    governing_body: "Bradford Council for Mosques",
    mosque_number: "0892",
    primary_color: "#15803d",
    secondary_color: "#f0fdf4",
    support_email: "office@alfalah-bradford.demo",
    support_phone: "01274 555010",
    secretary_name: "Mohammed Sadiq",
    secretary_phone: "01274 555011",
    secretary_address: "Al-Falah Centre, 1 Carlisle Road, Bradford BD8 8AS",
    service_schedule: "Jumu'ah 13:00. Daily prayers, weekly Mehfil and Qur'an circle.",
    service_location: "Al-Falah Islamic Centre, Carlisle Road, Bradford BD8 8AS",
    service_location_url: "https://maps.google.com/?q=Al+Falah+Bradford",
    accessibility_notes: "Wheelchair access via side entrance. Accessible wudu area fitted.",
    default_dress_code: "Modest dress appreciated throughout the centre.",
    hmrc_charity_reference: "MOSQUEPAY-SUN-0892",
    gift_aid_pack_name: "Al-Falah Bradford Gift Aid",
    gift_aid_pack_email: "treasurer@alfalah-bradford.demo",
    charity_donation_url: "https://donate.mosquepay.demo/al-falah",
    officers: [
      { full_name: "Imam Pir Abdul Qadir", office_title: "Imam", rank: "Imam" },
      { full_name: "Mohammed Sadiq", office_title: "Secretary", rank: "Member" },
      { full_name: "Ghulam Mustafa", office_title: "Treasurer", rank: "Member" },
      { full_name: "Rukhsana Bibi", office_title: "Women's Section Lead", rank: "Member" },
    ],
    member_names: ["Imran Sharif", "Nadia Akhtar", "Shahid Mahmood", "Lubna Aslam"],
    newcomer_names: [
      { first: "Usman", last: "Khan", stage: "membership decision_pending" },
      { first: "Sana", last: "Bibi", stage: "initial_contact" },
    ],
  },
  {
    slug: "noor-ul-islam-london",
    name: "Noor Ul Islam Masjid",
    denomination: "Sunni",
    city: "London",
    country: "United Kingdom",
    tagline: "Open doors and open hearts in East London.",
    governing_body: "East London Mosque Network",
    mosque_number: "3310",
    primary_color: "#b91c1c",
    secondary_color: "#fef2f2",
    support_email: "office@noorulislam-london.demo",
    support_phone: "020 8536 4740",
    secretary_name: "Yasmin Choudhury",
    secretary_phone: "020 8536 4741",
    secretary_address: "Noor Ul Islam, 67 Dawlish Road, Leyton, London E10 6QW",
    service_schedule: "Jumu'ah 13:30. Community iftar in Ramadan. Refreshments after Isha.",
    service_location: "Noor Ul Islam Masjid, Dawlish Road, Leyton, London E10 6QW",
    service_location_url: "https://maps.google.com/?q=Noor+Ul+Islam+Leyton",
    accessibility_notes: "Level access throughout. Accessible toilets on ground floor.",
    default_dress_code: "Modest dress; all welcome.",
    hmrc_charity_reference: "MOSQUEPAY-SUN-3310",
    gift_aid_pack_name: "Noor Ul Islam Gift Aid",
    gift_aid_pack_email: "treasurer@noorulislam-london.demo",
    charity_donation_url: null,
    officers: [
      { full_name: "Imam Abdul Hakim", office_title: "Imam", rank: "Imam" },
      { full_name: "Yasmin Choudhury", office_title: "Secretary", rank: "Member" },
      { full_name: "Shafiq Uddin", office_title: "Treasurer", rank: "Member" },
      { full_name: "Mahmudur Rahman", office_title: "Youth Coordinator", rank: "Member" },
    ],
    member_names: ["Faisal Ahmed", "Ruqayyah Begum", "Tanvir Islam", "Nusrat Jahan"],
    newcomer_names: [
      { first: "Aaron", last: "Webb", stage: "new" },
      { first: "Amira", last: "Shah", stage: "expression_of_interest" },
    ],
  },
  {
    slug: "masjid-al-rahma-manchester",
    name: "Masjid Al-Rahma",
    denomination: "Sunni (Salafi)",
    city: "Manchester",
    country: "United Kingdom",
    tagline: "Worship rooted in the Qur'an and Sunnah.",
    governing_body: "Greater Manchester Mosques Network",
    mosque_number: "1145",
    primary_color: "#1d4ed8",
    secondary_color: "#eff6ff",
    support_email: "office@alrahma-manchester.demo",
    support_phone: "0161 274 7120",
    secretary_name: "Khalid Mahmoud",
    secretary_phone: "0161 274 7121",
    secretary_address: "Masjid Al-Rahma, City Road, Hulme, Manchester M15 5GU",
    service_schedule: "Jumu'ah 13:15. Daily prayers and weekly tafsir Wed 19:30.",
    service_location: "Masjid Al-Rahma, City Road, Manchester M15 5GU",
    service_location_url: "https://maps.google.com/?q=Masjid+Al+Rahma+Manchester",
    accessibility_notes: "Ramp and lift to prayer area. Accessible wudu facilities.",
    default_dress_code: "Modest dress welcome.",
    hmrc_charity_reference: "MOSQUEPAY-SUN-1145",
    gift_aid_pack_name: "Masjid Al-Rahma Gift Aid",
    gift_aid_pack_email: "finance@alrahma-manchester.demo",
    charity_donation_url: null,
    officers: [
      { full_name: "Imam Abdullah Ar-Rahman", office_title: "Imam", rank: "Imam" },
      { full_name: "Khalid Mahmoud", office_title: "Secretary", rank: "Member" },
      { full_name: "Saeed Al-Amin", office_title: "Treasurer", rank: "Member" },
      { full_name: "Bilal Osei", office_title: "Welfare Lead", rank: "Member" },
    ],
    member_names: ["Idris Conteh", "Hawa Jallow", "Ayoub Benali"],
    newcomer_names: [
      { first: "David", last: "Thompson", stage: "welcomed" },
      { first: "Sumaya", last: "Ali", stage: "initial_contact" },
    ],
  },
  {
    slug: "glasgow-central-masjid",
    name: "Glasgow Central Masjid",
    denomination: "Sunni",
    city: "Glasgow",
    country: "United Kingdom",
    tagline: "Serving Muslims across the west of Scotland.",
    governing_body: "Scottish Mosques Network",
    mosque_number: "2201",
    primary_color: "#0e7490",
    secondary_color: "#ecfeff",
    support_email: "office@glasgow-central.demo",
    support_phone: "0141 709 4020",
    secretary_name: "Adnan Yousaf",
    secretary_phone: "0141 709 4021",
    secretary_address: "Glasgow Central Masjid, 1 Mosque Avenue, Glasgow G5 9TA",
    service_schedule: "Jumu'ah 13:00 & 13:45. Daily prayers and youth halaqah Fri 19:00.",
    service_location: "Glasgow Central Masjid, Mosque Avenue, Glasgow G5 9TA",
    service_location_url: "https://maps.google.com/?q=Glasgow+Central+Mosque",
    accessibility_notes: "Step-free access. Family and women's facilities available.",
    default_dress_code: "Modest dress.",
    hmrc_charity_reference: "MOSQUEPAY-SUN-2201",
    gift_aid_pack_name: "Glasgow Central Masjid Gift Aid",
    gift_aid_pack_email: "treasurer@glasgow-central.demo",
    charity_donation_url: "https://donate.mosquepay.demo/glasgow-central",
    officers: [
      { full_name: "Imam Mohammed Aslam", office_title: "Imam", rank: "Imam" },
      { full_name: "Adnan Yousaf", office_title: "Secretary", rank: "Member" },
      { full_name: "Waseem Akram", office_title: "Treasurer", rank: "Member" },
      { full_name: "Sajid Hussain", office_title: "Trustee", rank: "Member" },
    ],
    member_names: ["Asif Mahmood", "Farah Iqbal", "Rashid Ali", "Amina Yusuf"],
    newcomer_names: [
      { first: "Robert", last: "Mitchell", stage: "service_scheduled" },
      { first: "Hamza", last: "Walton", stage: "new" },
    ],
  },
  {
    slug: "husaini-islamic-centre",
    name: "Husaini Islamic Centre",
    denomination: "Shia (Ithna Ashari)",
    city: "London",
    country: "United Kingdom",
    tagline: "A centre of worship, learning and majalis in North London.",
    governing_body: "Council of European Jamaats",
    mosque_number: "5520",
    primary_color: "#1e3a8a",
    secondary_color: "#eef2ff",
    support_email: "office@husaini-centre.demo",
    support_phone: "020 8205 4275",
    secretary_name: "Murtaza Lakha",
    secretary_phone: "020 8205 4276",
    secretary_address: "Husaini Islamic Centre, Wood Lane, Stanmore, London HA7 4LQ",
    service_schedule: "Jumu'ah 13:00. Daily prayers, weekly majlis and Madrasah Sunday 10:00.",
    service_location: "Husaini Islamic Centre, Wood Lane, Stanmore, London HA7 4LQ",
    service_location_url: "https://maps.google.com/?q=Husaini+Islamic+Centre+Stanmore",
    accessibility_notes: "Hearing loop. Wheelchair access to main hall and imambargah.",
    default_dress_code: "Modest dress; head covering for women.",
    hmrc_charity_reference: "MOSQUEPAY-SHI-5520",
    gift_aid_pack_name: "Husaini Centre Gift Aid",
    gift_aid_pack_email: "treasurer@husaini-centre.demo",
    charity_donation_url: null,
    officers: [
      { full_name: "Sheikh Ali Raza", office_title: "Resident Aalim", rank: "Imam" },
      { full_name: "Murtaza Lakha", office_title: "Secretary", rank: "Member" },
      { full_name: "Abbas Jaffer", office_title: "Treasurer", rank: "Member" },
      { full_name: "Zahra Hasham", office_title: "Women's Section Lead", rank: "Member" },
    ],
    member_names: ["Hussein Dharsi", "Fatema Kassam", "Mohsin Walji"],
    newcomer_names: [
      { first: "Aliyah", last: "Premji", stage: "expression_of_interest" },
    ],
  },
  {
    slug: "suleymaniye-masjid-london",
    name: "Süleymaniye Masjid",
    denomination: "Sunni (Turkish)",
    city: "London",
    country: "United Kingdom",
    tagline: "Serving the Turkish-speaking Muslim community of London.",
    governing_body: "UK Turkish Islamic Trust",
    mosque_number: "7703",
    primary_color: "#7c3aed",
    secondary_color: "#f5f3ff",
    support_email: "office@suleymaniye-london.demo",
    support_phone: "020 7613 8010",
    secretary_name: "Mehmet Yılmaz",
    secretary_phone: "020 7613 8011",
    secretary_address: "Süleymaniye Masjid, 212 Kingsland Road, London E2 8AX",
    service_schedule: "Jumu'ah 13:30. Daily prayers, Qur'an courses and community kitchen.",
    service_location: "Süleymaniye Masjid, Kingsland Road, London E2 8AX",
    service_location_url: "https://maps.google.com/?q=Suleymaniye+Mosque+London",
    accessibility_notes: "Full wheelchair access. Children's classes available at weekends.",
    default_dress_code: "Modest dress; all welcome.",
    hmrc_charity_reference: "MOSQUEPAY-SUN-7703",
    gift_aid_pack_name: "Süleymaniye Masjid Gift Aid",
    gift_aid_pack_email: "finance@suleymaniye-london.demo",
    charity_donation_url: "https://donate.mosquepay.demo/suleymaniye",
    officers: [
      { full_name: "Imam Hüseyin Demir", office_title: "Imam", rank: "Imam" },
      { full_name: "Mehmet Yılmaz", office_title: "Secretary", rank: "Member" },
      { full_name: "Ahmet Kaya", office_title: "Treasurer", rank: "Member" },
      { full_name: "Elif Şahin", office_title: "Women's Section Lead", rank: "Member" },
    ],
    member_names: ["Emre Aydın", "Zeynep Çelik", "Mustafa Öztürk", "Hatice Arslan"],
    newcomer_names: [
      { first: "Kerem", last: "Doğan", stage: "initial_contact" },
      { first: "Selin", last: "Yıldız", stage: "new" },
    ],
  },
  {
    slug: "tawakal-masjid-cardiff",
    name: "Tawakal Masjid",
    denomination: "Sunni (Somali community)",
    city: "Cardiff",
    country: "United Kingdom",
    tagline: "A spiritual home for the Somali and wider Muslim community in Cardiff.",
    governing_body: "Muslim Council of Wales",
    mosque_number: "4410",
    primary_color: "#b45309",
    secondary_color: "#fffbeb",
    support_email: "office@tawakal-cardiff.demo",
    support_phone: "029 2045 7780",
    secretary_name: "Abdirahman Hassan",
    secretary_phone: "029 2045 7781",
    secretary_address: "Tawakal Masjid, 52 Crwys Road, Cathays, Cardiff CF24 4NN",
    service_schedule: "Jumu'ah 13:15. Daily prayers, dugsi classes and community lunch Tue 12:00.",
    service_location: "Tawakal Masjid, Crwys Road, Cardiff CF24 4NN",
    service_location_url: "https://maps.google.com/?q=Tawakal+Masjid+Cardiff",
    accessibility_notes: "Lift to hall. Food bank and welfare advice on site.",
    default_dress_code: "Modest dress; all welcome.",
    hmrc_charity_reference: "MOSQUEPAY-SUN-4410",
    gift_aid_pack_name: "Tawakal Masjid Gift Aid",
    gift_aid_pack_email: "treasurer@tawakal-cardiff.demo",
    charity_donation_url: null,
    officers: [
      { full_name: "Sheikh Abdullahi Nur", office_title: "Imam", rank: "Imam" },
      { full_name: "Abdirahman Hassan", office_title: "Secretary", rank: "Member" },
      { full_name: "Mohamed Farah", office_title: "Treasurer", rank: "Member" },
      { full_name: "Hodan Ahmed", office_title: "Welfare Lead", rank: "Member" },
    ],
    member_names: ["Ismail Warsame", "Sahra Jama", "Yusuf Omar"],
    newcomer_names: [
      { first: "Mahad", last: "Ali", stage: "approved" },
      { first: "Iman", last: "Said", stage: "expression_of_interest" },
    ],
  },
  {
    slug: "leeds-grand-masjid",
    name: "Leeds Grand Masjid",
    denomination: "Sunni",
    city: "Leeds",
    country: "United Kingdom",
    tagline: "Orthodox worship and community service for the people of Leeds.",
    governing_body: "Leeds Muslim Forum",
    mosque_number: "1208",
    primary_color: "#0f172a",
    secondary_color: "#f1f5f9",
    support_email: "office@leeds-grand.demo",
    support_phone: "0113 486 3847",
    secretary_name: "Nabeel Akhtar",
    secretary_phone: "0113 486 3848",
    secretary_address: "Leeds Grand Masjid, 9 Woodsley Road, Hyde Park, Leeds LS3 1DT",
    service_schedule: "Jumu'ah 13:00 & 13:45. Daily prayers, tajweed classes and seerah circle.",
    service_location: "Leeds Grand Masjid, Woodsley Road, Leeds LS3 1DT",
    service_location_url: "https://maps.google.com/?q=Leeds+Grand+Mosque",
    accessibility_notes: "Please contact the office for accessibility arrangements.",
    default_dress_code: "Modest dress; head covering for women in the prayer hall.",
    hmrc_charity_reference: "MOSQUEPAY-SUN-1208",
    gift_aid_pack_name: "Leeds Grand Masjid Gift Aid",
    gift_aid_pack_email: "treasurer@leeds-grand.demo",
    charity_donation_url: null,
    officers: [
      { full_name: "Imam Tahir Mahmood", office_title: "Imam", rank: "Imam" },
      { full_name: "Nabeel Akhtar", office_title: "Secretary", rank: "Member" },
      { full_name: "Kamran Sheikh", office_title: "Treasurer", rank: "Member" },
      { full_name: "Sufyan Malik", office_title: "Trustee", rank: "Member" },
    ],
    member_names: ["Adeel Rashid", "Sumaiya Khan", "Naveed Anwar"],
    newcomer_names: [
      { first: "Bilal", last: "Grant", stage: "initial_contact" },
      { first: "Noor", last: "Saleh", stage: "new" },
    ],
  },
];

export function demoEmailFor(slug: string, label: string) {
  const safe = slug.replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
  return `seed+${safe}-${label}@mosquepay-demo.test`;
}
