"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import {
  CheckCircle2,
  ChevronDown,
  ChevronUp,
  Copy,
  Download,
  Loader2,
  Plug,
  PlugZap,
  RefreshCw,
  Trash2,
  XCircle,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Tabs,
  TabsContent,
  TabsList,
  TabsTrigger,
} from "@/components/ui/tabs";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { ConfirmActionDialog } from "@/components/ui/confirm-action-dialog";

type Provider =
  | "google_calendar"
  | "outlook"
  | "mailchimp"
  | "brevo"
  | "xero"
  | "quickbooks";

type Credential = {
  provider: Provider;
  enabled: boolean;
  metadata: Record<string, unknown>;
  expires_at: string | null;
};

type Job = {
  id: string;
  job_type: string;
  status: "queued" | "in_progress" | "succeeded" | "failed" | "cancelled";
  scheduled_at: string;
  finished_at: string | null;
  attempts: number;
  last_error: string | null;
};

type MooovConnection = {
  merchantId: string;
  status: string;
  metadata: Record<string, unknown>;
} | null;

type FieldDef = {
  key: string;
  label: string;
  type: "text" | "password" | "url";
  hint?: string;
  storage: "metadata" | "access_token" | "refresh_token";
};

type ProviderMeta = {
  label: string;
  group: "Calendar" | "Email" | "Accounting";
  logo: string;
  blurb: string;
  fields: FieldDef[];
  comingSoon?: boolean;
};

const PROVIDER_META: Record<Provider, ProviderMeta> = {
  google_calendar: {
    label: "Google Calendar",
    group: "Calendar",
    comingSoon: true,
    logo: "/brand/integrations/google-calendar.svg",
    blurb:
      "Push mosque services to a shared Google Calendar. Paste an OAuth refresh token plus the target calendar ID.",
    fields: [
      {
        key: "refresh",
        label: "OAuth refresh token",
        type: "password",
        storage: "refresh_token",
        hint: "Generated by your Google Cloud OAuth client.",
      },
      {
        key: "calendar_id",
        label: "Calendar ID",
        type: "text",
        storage: "metadata",
        hint: "Usually looks like mosque@example.com or a long calendar id.",
      },
    ],
  },
  outlook: {
    label: "Microsoft Outlook",
    group: "Calendar",
    comingSoon: true,
    logo: "/brand/integrations/outlook.svg",
    blurb:
      "Sync services into a shared Outlook / Microsoft 365 calendar. Provide an app refresh token and target calendar.",
    fields: [
      {
        key: "refresh",
        label: "Refresh token",
        type: "password",
        storage: "refresh_token",
      },
      {
        key: "calendar_id",
        label: "Calendar ID",
        type: "text",
        storage: "metadata",
        hint: "From Microsoft Graph (e.g. AAMkAD...).",
      },
    ],
  },
  mailchimp: {
    label: "Mailchimp",
    group: "Email",
    comingSoon: true,
    logo: "/brand/integrations/mailchimp.svg",
    blurb:
      "Mirror your members and newcomers into a Mailchimp audience for newsletters.",
    fields: [
      {
        key: "api_key",
        label: "API key",
        type: "password",
        storage: "access_token",
        hint: "Found under Account > Extras > API keys.",
      },
      {
        key: "audience_id",
        label: "Audience (list) ID",
        type: "text",
        storage: "metadata",
      },
      {
        key: "data_center",
        label: "Data center",
        type: "text",
        storage: "metadata",
        hint: "The us1 / eu1 prefix from your Mailchimp URL.",
      },
    ],
  },
  brevo: {
    label: "Brevo (Sendinblue)",
    group: "Email",
    comingSoon: true,
    logo: "/brand/integrations/brevo.png",
    blurb:
      "Send transactional and bulk emails through Brevo and sync contact lists.",
    fields: [
      {
        key: "api_key",
        label: "API key",
        type: "password",
        storage: "access_token",
      },
      {
        key: "list_id",
        label: "Contact list ID",
        type: "text",
        storage: "metadata",
      },
      {
        key: "sender_email",
        label: "Verified sender email",
        type: "text",
        storage: "metadata",
      },
    ],
  },
  xero: {
    label: "Xero",
    group: "Accounting",
    comingSoon: true,
    logo: "/brand/integrations/xero.svg",
    blurb:
      "Push the treasurer ledger into Xero. Use a long-lived OAuth refresh token from your Xero app.",
    fields: [
      {
        key: "refresh",
        label: "Refresh token",
        type: "password",
        storage: "refresh_token",
      },
      {
        key: "tenant_id",
        label: "Tenant (organisation) ID",
        type: "text",
        storage: "metadata",
      },
      {
        key: "bank_account_code",
        label: "Default bank account code",
        type: "text",
        storage: "metadata",
        hint: "e.g. 090. Used when creating bank transactions.",
      },
    ],
  },
  quickbooks: {
    label: "QuickBooks",
    group: "Accounting",
    comingSoon: true,
    logo: "/brand/integrations/quickbooks.svg",
    blurb:
      "Push payments, giving and donations into QuickBooks Online. Provide an OAuth refresh token and realm ID.",
    fields: [
      {
        key: "refresh",
        label: "Refresh token",
        type: "password",
        storage: "refresh_token",
      },
      {
        key: "realm_id",
        label: "Realm ID",
        type: "text",
        storage: "metadata",
      },
      {
        key: "income_account",
        label: "Default income account name",
        type: "text",
        storage: "metadata",
      },
    ],
  },
};

function fieldValue(
  field: FieldDef,
  cred: Credential | undefined,
  draft: Record<string, string> | undefined
): string {
  if (draft && field.key in draft) return draft[field.key];
  if (!cred) return "";
  if (field.storage === "metadata") {
    const v = cred.metadata?.[field.key];
    return typeof v === "string" ? v : "";
  }
  return field.type === "password" && cred.enabled ? "••••••••" : "";
}

export function IntegrationsClient({
  mosqueSlug,
  mosqueName,
  credentials,
  jobs,
  mooovConnection,
  initialFeedback,
}: {
  mosqueSlug: string;
  mosqueName: string;
  credentials: Credential[];
  jobs: Job[];
  mooovConnection: MooovConnection;
  initialFeedback?: string | null;
}) {
  const router = useRouter();
  const [busy, setBusy] = useState<string | null>(null);
  const [feedback, setFeedback] = useState<string | null>(initialFeedback ?? null);
  const [open, setOpen] = useState<Provider | null>(null);
  const [disconnectingProvider, setDisconnectingProvider] = useState<Provider | null>(null);
  const [confirmMooovDisconnect, setConfirmMooovDisconnect] = useState(false);
  const [drafts, setDrafts] = useState<Record<Provider, Record<string, string>>>(
    {
      google_calendar: {},
      outlook: {},
      mailchimp: {},
      brevo: {},
      xero: {},
      quickbooks: {},
    }
  );

  const credByProvider = new Map(credentials.map((c) => [c.provider, c]));

  function setDraftField(provider: Provider, key: string, value: string) {
    setDrafts((prev) => ({
      ...prev,
      [provider]: { ...prev[provider], [key]: value },
    }));
  }

  async function saveProvider(provider: Provider, opts?: { enabled?: boolean }) {
    const meta = PROVIDER_META[provider];
    const cred = credByProvider.get(provider);
    const draft = drafts[provider] ?? {};
    const metadata: Record<string, unknown> = {
      ...(cred?.metadata ?? {}),
    };
    let access_token: string | null | undefined = undefined;
    let refresh_token: string | null | undefined = undefined;

    for (const field of meta.fields) {
      const raw = draft[field.key];
      if (raw === undefined) continue;
      const trimmed = raw.trim();
      if (field.storage === "metadata") {
        if (trimmed) metadata[field.key] = trimmed;
        else delete metadata[field.key];
      } else if (field.storage === "access_token") {
        access_token = trimmed === "" ? null : trimmed;
      } else if (field.storage === "refresh_token") {
        refresh_token = trimmed === "" ? null : trimmed;
      }
    }

    setBusy(`save:${provider}`);
    try {
      const res = await fetch(`/api/integrations/${provider}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          enabled: opts?.enabled ?? cred?.enabled ?? true,
          metadata,
          ...(access_token !== undefined ? { access_token } : {}),
          ...(refresh_token !== undefined ? { refresh_token } : {}),
        }),
      });
      if (!res.ok) {
        const body = await res.json().catch(() => ({}));
        throw new Error(body.error ?? "Could not save provider.");
      }
      setDrafts((prev) => ({ ...prev, [provider]: {} }));
      setFeedback(`${meta.label} saved.`);
      router.refresh();
    } catch (error) {
      setFeedback(error instanceof Error ? error.message : "Save failed.");
    } finally {
      setBusy(null);
    }
  }

  async function toggleProvider(provider: Provider) {
    const cred = credByProvider.get(provider);
    if (!cred) {
      setOpen(provider);
      setFeedback(`Add credentials for ${PROVIDER_META[provider].label} below.`);
      return;
    }
    await saveProvider(provider, { enabled: !cred.enabled });
  }

  async function disconnect(provider: Provider) {
    setBusy(`delete:${provider}`);
    try {
      const res = await fetch(`/api/integrations/${provider}`, {
        method: "DELETE",
      });
      if (!res.ok) throw new Error("Could not disconnect.");
      setFeedback(`${PROVIDER_META[provider].label} disconnected.`);
      router.refresh();
    } catch (error) {
      setFeedback(error instanceof Error ? error.message : "Disconnect failed.");
    } finally {
      setBusy(null);
    }
  }

  async function disconnectMooov() {
    setBusy("delete:mooov");
    try {
      const res = await fetch("/api/mooov/disconnect", { method: "POST" });
      const body = await res.json().catch(() => ({}));
      if (!res.ok) {
        throw new Error(body.error ?? "Could not disconnect Mooov.");
      }
      setFeedback(
        body.revoked_remotely === false
          ? "Mooov already revoked on their side. Local state cleared."
          : "Mooov disconnected."
      );
      router.refresh();
    } catch (error) {
      setFeedback(
        error instanceof Error ? error.message : "Disconnect failed."
      );
    } finally {
      setBusy(null);
    }
  }

  async function processQueue() {
    setBusy("process");
    try {
      const res = await fetch("/api/jobs/process?max=10", { method: "POST" });
      const data = await res.json();
      setFeedback(
        `Processed ${data.processed ?? 0}: ${data.succeeded ?? 0} ok, ${data.failed ?? 0} failed.`
      );
      router.refresh();
    } catch (error) {
      setFeedback(error instanceof Error ? error.message : "Process failed.");
    } finally {
      setBusy(null);
    }
  }

  function copy(value: string) {
    navigator.clipboard?.writeText(value);
    setFeedback("Copied to clipboard.");
  }

  const calendarFeedUrl = `${typeof window !== "undefined" ? window.location.origin : ""}/api/calendar/mosque/${mosqueSlug}`;

  const grouped: Record<string, Provider[]> = {
    Calendar: [],
    Email: [],
    Accounting: [],
  };
  for (const provider of Object.keys(PROVIDER_META) as Provider[]) {
    grouped[PROVIDER_META[provider].group].push(provider);
  }

  return (
    <div className="space-y-4 sm:space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-slate-900">Integrations &amp; jobs</h1>
        <p className="mt-1 text-sm text-slate-500">
          Connect calendar, email, and accounting tools to {mosqueName}, and
          monitor background jobs (emails, giving runs, exports, reconciliation).
        </p>
      </div>

      {feedback && (
        <div className="rounded-xl border border-blue-200 bg-blue-50 px-4 py-2 text-sm text-blue-900">
          {feedback}
        </div>
      )}

      <Tabs defaultValue="providers">
        <TabsList>
          <TabsTrigger value="providers">Providers</TabsTrigger>
          <TabsTrigger value="exports">Exports &amp; feeds</TabsTrigger>
          <TabsTrigger value="jobs">Background jobs</TabsTrigger>
        </TabsList>

        <TabsContent value="providers" className="space-y-4">
          <div className="rounded-2xl border border-slate-200 bg-white shadow-sm">
            <div className="flex flex-col gap-4 px-5 py-4 md:flex-row md:items-center md:justify-between">
              <div className="flex items-start gap-3">
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img
                  src="/brand/mooov-logo.png"
                  alt="Mooov"
                  className="mt-0.5 h-6 w-auto"
                />
                <div>
                  <div className="flex flex-wrap items-center gap-2">
                    <h2 className="text-base font-semibold text-slate-900">
                      Mooov Connect
                    </h2>
                    {mooovConnection?.status === "active" ? (
                      <Badge variant="secondary" className="bg-emerald-100 text-emerald-700">
                        <CheckCircle2 className="mr-1 h-3 w-3" /> Connected
                      </Badge>
                    ) : mooovConnection?.status === "revoked" ? (
                      <Badge variant="outline" className="bg-slate-100 text-slate-700">
                        <XCircle className="mr-1 h-3 w-3" /> Disconnected
                      </Badge>
                    ) : mooovConnection?.status === "needs_repair" ? (
                      <Badge variant="outline" className="bg-amber-100 text-amber-800">
                        <XCircle className="mr-1 h-3 w-3" /> Needs repair
                      </Badge>
                    ) : mooovConnection ? (
                      <Badge variant="outline">
                        <XCircle className="mr-1 h-3 w-3" /> {mooovConnection.status}
                      </Badge>
                    ) : (
                      <Badge variant="outline">
                        <XCircle className="mr-1 h-3 w-3" /> Not connected
                      </Badge>
                    )}
                  </div>
                  <p className="mt-1 text-xs text-slate-500">
                    Connect this mosque to Mooov for giving and payment processing.
                    MosquePay uses the platform credential, while each mosque grants
                    its own merchant access.
                  </p>
                  {mooovConnection?.merchantId ? (
                    <p className="mt-2 font-mono text-[11px] text-slate-500">
                      Merchant: {mooovConnection.merchantId}
                    </p>
                  ) : null}
                </div>
              </div>
              <div className="flex flex-wrap items-center gap-2">
                <a href="/api/mooov/connect/start">
                  <Button size="sm" variant={mooovConnection ? "outline" : "primary"}>
                    {mooovConnection ? (
                      <RefreshCw className="mr-1 h-3 w-3" />
                    ) : (
                      <Plug className="mr-1 h-3 w-3" />
                    )}
                    {mooovConnection?.status === "active"
                      ? "Reconnect Mooov"
                      : mooovConnection
                        ? "Reconnect Mooov"
                        : "Connect Mooov"}
                  </Button>
                </a>
                {mooovConnection &&
                (mooovConnection.status === "active" ||
                  mooovConnection.status === "needs_repair") ? (
                  <Button
                    size="sm"
                    variant="outline"
                    onClick={() => setConfirmMooovDisconnect(true)}
                    disabled={busy === "delete:mooov"}
                  >
                    {busy === "delete:mooov" ? (
                      <Loader2 className="mr-1 h-3 w-3 animate-spin" />
                    ) : (
                      <PlugZap className="mr-1 h-3 w-3" />
                    )}
                    Disconnect
                  </Button>
                ) : null}
              </div>
            </div>
          </div>

          {Object.entries(grouped).map(([groupName, providers]) => (
            <div
              key={groupName}
              className="rounded-2xl border border-slate-200 bg-white shadow-sm"
            >
              <div className="border-b border-slate-100 px-5 py-3">
                <h2 className="text-base font-semibold text-slate-900">
                  {groupName}
                </h2>
              </div>
              <div className="divide-y divide-slate-100">
                {providers.map((provider) => {
                  const meta = PROVIDER_META[provider];
                  const cred = credByProvider.get(provider);
                  const isOpen = open === provider;
                  const comingSoon = meta.comingSoon === true;
                  return (
                    <div
                      key={provider}
                      className={comingSoon ? "px-5 py-3 opacity-75" : "px-5 py-3"}
                    >
                      <div className="flex items-center justify-between gap-4">
                        <div className="flex items-center gap-3">
                          <div className="flex h-8 w-8 shrink-0 items-center justify-center overflow-hidden rounded-md bg-white ring-1 ring-slate-200">
                            {/* eslint-disable-next-line @next/next/no-img-element */}
                            <img
                              src={meta.logo}
                              alt={`${meta.label} logo`}
                              className="h-5 w-5 object-contain"
                            />
                          </div>
                          <div>
                            <p className="text-sm font-medium text-slate-900">
                              {meta.label}
                            </p>
                            <p className="text-xs text-slate-500">
                              {comingSoon
                                ? "Coming soon"
                                : cred?.enabled
                                ? "Connected and enabled"
                                : cred
                                ? "Saved but disabled"
                                : "Not connected"}
                            </p>
                          </div>
                        </div>
                        <div className="flex items-center gap-2">
                          {comingSoon ? (
                            <Badge
                              variant="secondary"
                              className="bg-amber-50 text-amber-800"
                            >
                              Coming soon
                            </Badge>
                          ) : cred?.enabled ? (
                            <Badge variant="secondary" className="bg-emerald-100 text-emerald-700">
                              <CheckCircle2 className="mr-1 h-3 w-3" /> Active
                            </Badge>
                          ) : (
                            <Badge variant="outline">
                              <XCircle className="mr-1 h-3 w-3" /> Off
                            </Badge>
                          )}
                          {!comingSoon && (
                            <>
                              <Button
                                size="sm"
                                variant="outline"
                                disabled={busy === `save:${provider}`}
                                onClick={() => toggleProvider(provider)}
                              >
                                {cred?.enabled ? "Disable" : "Enable"}
                              </Button>
                              <Button
                                size="sm"
                                variant="ghost"
                                onClick={() =>
                                  setOpen(isOpen ? null : provider)
                                }
                              >
                                {isOpen ? (
                                  <>
                                    Hide <ChevronUp className="ml-1 h-3 w-3" />
                                  </>
                                ) : (
                                  <>
                                    Configure <ChevronDown className="ml-1 h-3 w-3" />
                                  </>
                                )}
                              </Button>
                            </>
                          )}
                        </div>
                      </div>

                      {isOpen && !comingSoon && (
                        <div className="mt-3 rounded-xl border border-slate-200 bg-slate-50/60 p-4">
                          <p className="text-xs text-slate-600">{meta.blurb}</p>
                          <div className="mt-3 grid grid-cols-1 gap-3 md:grid-cols-2">
                            {meta.fields.map((field) => (
                              <div key={field.key} className="space-y-1">
                                <Label htmlFor={`${provider}-${field.key}`} className="text-xs">
                                  {field.label}
                                </Label>
                                <Input
                                  id={`${provider}-${field.key}`}
                                  type={field.type === "password" ? "password" : "text"}
                                  value={fieldValue(field, cred, drafts[provider])}
                                  placeholder={
                                    field.type === "password" && cred?.enabled
                                      ? "Stored. Enter a new value to replace."
                                      : ""
                                  }
                                  onChange={(e) =>
                                    setDraftField(provider, field.key, e.target.value)
                                  }
                                />
                                {field.hint && (
                                  <p className="text-[11px] text-slate-500">{field.hint}</p>
                                )}
                              </div>
                            ))}
                          </div>
                          <div className="mt-3 flex flex-wrap gap-2">
                            <Button
                              size="sm"
                              onClick={() => saveProvider(provider, { enabled: true })}
                              disabled={busy === `save:${provider}`}
                            >
                              {busy === `save:${provider}` ? (
                                <Loader2 className="mr-1 h-3 w-3 animate-spin" />
                              ) : null}
                              Save &amp; enable
                            </Button>
                            {cred && (
                              <Button
                                size="sm"
                                variant="outline"
                                onClick={() => setDisconnectingProvider(provider)}
                                disabled={busy === `delete:${provider}`}
                              >
                                <Trash2 className="mr-1 h-3 w-3" />
                                Disconnect
                              </Button>
                            )}
                          </div>
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
            </div>
          ))}
        </TabsContent>

        <TabsContent value="exports" className="space-y-4">
          <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
            <h2 className="text-base font-semibold text-slate-900">
              Public mosque calendar feed
            </h2>
            <p className="mt-1 text-xs text-slate-500">
              Subscribe to this URL from Google, Apple, or Outlook Calendar to
              keep published events in sync.
            </p>
            <div className="mt-3 flex flex-wrap items-center gap-2">
              <code className="break-all rounded bg-slate-100 px-2 py-1 text-xs">
                {calendarFeedUrl}
              </code>
              <Button size="sm" variant="outline" onClick={() => copy(calendarFeedUrl)}>
                <Copy className="mr-1 h-3 w-3" /> Copy
              </Button>
            </div>
          </div>

          <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
            <h2 className="text-base font-semibold text-slate-900">
              Accounting CSV exports
            </h2>
            <p className="mt-1 text-xs text-slate-500">
              Download the treasurer ledger pre-formatted for your accounting
              package. Payment integrations are not used; reconciliation runs
              from CSV bank statements only.
            </p>
            <div className="mt-3 flex flex-wrap gap-2">
              <a href="/api/admin/exports/accounting.csv?format=xero">
                <Button size="sm" variant="outline">
                  <Download className="mr-1 h-3 w-3" /> Xero CSV
                </Button>
              </a>
              <a href="/api/admin/exports/accounting.csv?format=quickbooks">
                <Button size="sm" variant="outline">
                  <Download className="mr-1 h-3 w-3" /> QuickBooks CSV
                </Button>
              </a>
              <a href="/api/admin/exports/accounting.csv">
                <Button size="sm" variant="outline">
                  <Download className="mr-1 h-3 w-3" /> Generic ledger CSV
                </Button>
              </a>
            </div>
          </div>
        </TabsContent>

        <TabsContent value="jobs">
          <div className="rounded-2xl border border-slate-200 bg-white shadow-sm">
            <div className="flex items-center justify-between border-b border-slate-100 px-5 py-3">
              <div>
                <h2 className="text-base font-semibold text-slate-900">
                  Recent jobs
                </h2>
                <p className="text-xs text-slate-500">
                  Configure cron at /api/jobs/process to drain the queue
                  automatically.
                </p>
              </div>
              <Button size="sm" onClick={processQueue} disabled={busy === "process"}>
                {busy === "process" ? (
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                ) : (
                  <Plug className="mr-2 h-4 w-4" />
                )}
                Process now
              </Button>
            </div>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Type</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead>Scheduled</TableHead>
                  <TableHead>Attempts</TableHead>
                  <TableHead>Error</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {jobs.length === 0 ? (
                  <TableRow>
                    <TableCell colSpan={5} className="py-6 text-center text-sm text-slate-500">
                      No jobs in the queue yet.
                    </TableCell>
                  </TableRow>
                ) : (
                  jobs.map((job) => (
                    <TableRow key={job.id}>
                      <TableCell className="text-sm font-mono">{job.job_type}</TableCell>
                      <TableCell>
                        <Badge
                          variant={job.status === "succeeded" ? "secondary" : "outline"}
                        >
                          {job.status}
                        </Badge>
                      </TableCell>
                      <TableCell className="text-xs text-slate-500">
                        {new Date(job.scheduled_at).toLocaleString("en-GB")}
                      </TableCell>
                      <TableCell className="text-sm">{job.attempts}</TableCell>
                      <TableCell className="text-xs text-red-600">
                        {job.last_error ?? ""}
                      </TableCell>
                    </TableRow>
                  ))
                )}
              </TableBody>
            </Table>
          </div>
        </TabsContent>
      </Tabs>
      <ConfirmActionDialog
        open={confirmMooovDisconnect}
        onOpenChange={(open) => !open && setConfirmMooovDisconnect(false)}
        title="Disconnect Mooov?"
        description={
          "This revokes the mosque's Mooov grant. New giving, donations, and event payments will fail until you reconnect. " +
          "Existing payments, refunds, and historical reports are unaffected. " +
          "You can reconnect any time -- the same merchant account is reused on reconnect."
        }
        confirmLabel="Disconnect Mooov"
        tone="danger"
        loading={busy === "delete:mooov"}
        onConfirm={async () => {
          await disconnectMooov();
          setConfirmMooovDisconnect(false);
        }}
      />
      <ConfirmActionDialog
        open={disconnectingProvider !== null}
        onOpenChange={(open) => !open && setDisconnectingProvider(null)}
        title="Disconnect integration?"
        description={
          disconnectingProvider
            ? `Stored tokens for ${PROVIDER_META[disconnectingProvider].label} will be removed.`
            : "Stored tokens will be removed."
        }
        confirmLabel="Disconnect"
        tone="danger"
        loading={
          disconnectingProvider
            ? busy === `delete:${disconnectingProvider}`
            : false
        }
        onConfirm={async () => {
          if (!disconnectingProvider) return;
          await disconnect(disconnectingProvider);
          setDisconnectingProvider(null);
        }}
      />
    </div>
  );
}
